---
abstract: 'Mojolicious::Lite webapp that lets you search (with regexp) and display CPAN modules documentation'
author:
  - 'Ahmad Syaltut <Isyaltut@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-perldolicious
provides:
  App::perldolicious:
    file: lib/App/perldolicious.pm
    version: 0.009
requires:
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  IO::Zlib: 1.10
  Module::CoreList: 2.91
  Module::Path: 0.09
  Mojo::JSON: 0
  Mojo::UserAgent: 0
  Mojolicious: 4.07
  Pod::Cpandoc: 0.15
  Scalar::Util: 0
  Storable: 0
resources:
  homepage: https://github.com/Syaltut/perl-App-perldolicious
  license: http://dev.perl.org/licenses/
  repository: git://github.com/Syaltut/perl-App-perldolicious.git
version: 0.009
x_test_requires:
  FindBin: 0
  Net::Ping: 0
  Test::Mojo: 0
  Test::More: 0
